### ISSUE TITLE
import nengo_dl error 'AttributeError: module 'nengo' has no attribute '__version__' '

### ISSUE THREAD

**Issue by xiyan524** [nengo/nengo-dl#101]
I'm trying to import nengo_dl(2.2.0), while it shows the following mistakes:

Traceback (most recent call last):
  File "/home/snn/LIF/test.py", line 2, in <module>
    import nengo_dl
  File "/home/anaconda3/envs/nengo_dl/lib/python3.5/site-packages/nengo_dl/__init__.py", line 32, in <module>
    from nengo_dl.compat import tf_compat
  File "/home/anaconda3/envs/nengo_dl/lib/python3.5/site-packages/nengo_dl/compat.py", line 53, in <module>
    if LooseVersion(nengo.__version__) < "3.0.0":
AttributeError: module 'nengo' has no attribute '__version__'

**Comment by drasmuss** [comment]
It seems like your `nengo` package is not installed correctly. You could try reinstalling via
```
pip uninstall nengo
pip install nengo
```
and see if that fixes it?

Another possibility is that you have a folder named `nengo` in the `home/snn/LIF` directory (so when it tries to `import nengo` it is importing that folder, rather than the nengo package).

**Comment by drasmuss** [comment]
I see that you opened up a forum thread as well https://forum.nengo.ai/t/import-nengo-dl/953, so I will close this issue and move the discussion there (as the forum is better for this kind of troubleshooting).
