### ISSUE TITLE
is that possible to create an spiking auto-encoder with nengo

### ISSUE THREAD

**Issue by ati6868** [nengo/nengo-dl#103]
Hi
In nengo , how can i implement autoencoder in spiking neural networks
is that possible in nengo?

**Comment by drasmuss** [comment]
There's an example of implementing an autoencoder in Nengo here https://www.nengo.ai/nengo-dl/examples/from-tensorflow.html

**Comment by ati6868** [comment]
Thank you very much for your response @drasmuss 
but one question
this link that you sent me ,is an autoencoder in spiking neural networks??
i guess it's not
and if it's not , do you have any idea how to convert it to anautoencoder in SNNs??

**Comment by drasmuss** [comment]
Yes, you would need to change the neuron model from `nengo.RectifiedLinear` to a spiking neuron model (e.g. `nengo.SpikingRectifiedLinear`), and then you would need to make sure that you are running the network for multiple timesteps during inference/evaluation.  Basically the same as this example https://www.nengo.ai/nengo-dl/examples/spiking-mnist.html, but you're training an autoencoder instead of a classification network.  But there's nothing qualitatively different about training an autoencoder, it's just a different network structure and training data.

**Comment by drasmuss** [comment]
Closing this since it seems like the question is answered, but if you have any other questions feel free to stop by the [forum](https://forum.nengo.ai/) and we can help out!
