### ISSUE TITLE
nengo_dl.Simulator returns runtime error with non-dev version

### ISSUE THREAD

**Issue by arkhodamoradi** [nengo/nengo-dl#40]
After installing _nengo_dl_ via pip: `pip install nengo-dl`, I tried simple provided examples and received _**runtime error: Cannot join thread before it is started**_.

This issue resolved for me by uninstalling the _nengo-dl_ and installing its development version:
`git clone https://github.com/nengo/nengo-dl.git`
`pip install -e ./nengo-dl`

**Comment by drasmuss** [comment]
This is due to an update in the `progressbar2` package.  You can either downgrade the `progressbar2` version (`pip install progressbar2<3.37.0`), or, as you noticed, the development version of `nengo-dl` is updated to work with the latest `progressbar2` version.  We'll try to get a release out this week that includes that fix.

**Comment by drasmuss** [comment]
Just released v0.6.2 which should resolve this.  Let me know if it doesn't for some reason, and I'll reopen the issue!

**Comment by arkhodamoradi** [comment]
Great! Thank you.
