### ISSUE TITLE
spiking-mnist.ipynb: TypeError: loss() missing 1 required positional argument: 'targets'

### ISSUE THREAD

**Issue by joh10891** [nengo/nengo-dl#70]
When attempting to run spiking-mnist.ipynb exactly as written in the example, I get 
`TypeError: loss() missing 1 required positional argument: 'targets' `

Any ideas what may be causing this, or possible solutions?

**Comment by drasmuss** [comment]
Your version of NengoDL does not match the example, so two possibilities:

1. You can use an earlier version of the example, corresponding to your installed NengoDL version (e.g., if you have the latest PyPI release it's [this version](https://www.nengo.ai/nengo-dl/v1.2.1/examples/spiking_mnist.html)).  There's a version dropdown in the bottom left that you can change to view the example for any previous NengoDL release.

2. You can do a [developer installation](https://www.nengo.ai/nengo-dl/installation.html#developer-installation) to get the most up-to-date version of NengoDL, which will match the most up-to-date example in the documentation.

Either one should work for you, let me know if you run into any problems.  We'll be doing a new release soon to bring the PyPI version up-to-date, I've just been delaying it a bit because it's a larger update that I want to be sure is battle tested.

**Comment by joh10891** [comment]
Fantastic, both methods seemed to work for me. I appreciate the quick reply!
